### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by wareck** [TCWORLD/ATTinyCore#10]
Hi,
I try to test the last version, and I've got this kind off error message:
"C:\Documents and Settings\Olivier\Mes documents\Arduino\hardware\tiny\cores\tiny/Arduino.h:125: error: 'port_to_output_PGM' has a previous declaration as 'const uint16_t port_to_output_PGM []"

Can you help me ?

Olivier

**Comment by TCWORLD** [comment]
the 'tiny' folder should be in "< Arduino dir >\hardware".

Also, what version of Arduino are you using?

**Comment by TCWORLD** [comment]
I'm closing this as you haven't responded. If this is still an issue, reopen it.
