### ISSUE TITLE
Any way to detect tiny core vs. regular core?

### ISSUE THREAD

**Issue by floe** [TCWORLD/ATTinyCore#13]
Based on whether it's running with your tiny core or the regular Arduino core, I'd like to have my Arduino library automatically switch between SPI.h or TinySoftwareSPI.h - is there any existing define I could reliably check for, or would it be an option to include something like

```
#define ATTinyCore 1
```

into tiny/.../Arduino.h ?

Or perhaps even better, add a define USE_SOFTWARE_SPI into pins_arduino.h ?

**Comment by TCWORLD** [comment]
I will add a #define in for the core and processor groups this evening. I will use ATTINYCORE as you have requested.

**Comment by floe** [comment]
Could you perhaps also include a define for USE_SOFTWARE_SPI in pins_arduino.h (where appropriate)? I think that might even be more useful - IIRC some ATtiny models do have hardware SPI, so just selecting based on the core would perhaps be a little coarse.
Thanks!

**Comment by floe** [comment]
Awesome, thanks!
