### ISSUE TITLE
ADC mux bits?

### ISSUE THREAD

**Issue by floe** [TCWORLD/ATTinyCore#14]
The current code seems to allow at most 8 ADC channels (due to 'pin & 0x07' here):
https://github.com/TCWORLD/ATTinyCore/blob/master/tiny/cores/tiny/wiring_analog.c#L61
Is this intentional, as some Tinys don't have more?

**Comment by TCWORLD** [comment]
That basically stems from other version of Arduino cores and I never really gave it much thought. Some do in fact have much more options. The other issue is that to maintain compatibility with the Arduino way of doing things, if the input selected is more than the number of digital inputs it subtracts NUM_DIGITAL_PINS from it. This is so you can use A0 for both digitalRead() and analogRead() and also use just 0 for analogRead() all to mean the same thing. As such if you want to use an ADMUX setting of >NUM_DIGITAL_PINS, you need to remember to add on NUM_DIGITAL_PINS. E.g. if you want 15 (temp sensor for some), you would have to set the pin to be NUM_DIGITAL_PINS+15.

I've corrected the code to allow more than 3 bits of MUX if the chip supports it. I haven't checked whether all chips have the MUX value as a sequential set of bits, but I assume they will.
