### ISSUE TITLE
add OSCCAL value for 2313

### ISSUE THREAD

**Issue by lestofante** [TCWORLD/ATTinyCore#17]
Michele Menniti found out in pins_Arduino.h is missing the lines:
//If Software Serial communications doesn't work, run the TinyTuner sketch provided with the core to give you a calibrated OSCCAL value.
//Change the value here with the tuned value. By default this option uses the default value which the compiler will optimise out.
# define TUNED_OSCCAL_VALUE                        OSCCAL

//e.g
//#define TUNED_OSCCAL_VALUE                        0x57

**Comment by TCWORLD** [comment]
This was fixed in the last commit - but due to a typo in the commit name (I put #11 not #16), it didn't get closed. See commit: 2dd1f05
