### ISSUE TITLE
Errors with HardwareSerial.cpp

### ISSUE THREAD

**Issue by whiteglint143** [TCWORLD/ATTinyCore#19]
I downloaded the latest cores as of 7 June 2014 and I get the following error when trying to compile a basic "blink" sketch with any board. I was able to do a quick n' dirty fix by using the previous HardwareSerial .cpp and .h files.

Arduino/hardware/ATTinyCore/cores/tiny/HardwareSerial.cpp:147:2: error: #else after #else
Arduino/hardware/ATTinyCore/cores/tiny/HardwareSerial.cpp:77:1: error: the conditional began here
Arduino/hardware/ATTinyCore/cores/tiny/HardwareSerial.cpp:33:1: error: unterminated #if

**Comment by TCWORLD** [comment]
I'll correct that this evening, must have missed an #else when I was changing things around.

**Comment by whiteglint143** [comment]
I poked around for a little bit with it. I am not as experienced as you but this may help out some.

The errors for 147:2 and 77:1 seem to have to deal with line 125 and 147. 
I changed the #else to #elif in line 125 and it cleared the two previously mentioned errors. 

For the 33:1 error, I had to change line 154 #if to #elif and my sketch was able to compile 

Hope this helps.

**Comment by TCWORLD** [comment]
Fixed. Need to stop coding at midnight!
