### ISSUE TITLE
Possible wrong pin assignment for ATTINY861A

### ISSUE THREAD

**Issue by greenwoodma** [TCWORLD/ATTinyCore#2]
I think (although I haven't yet got a ATTINY861A in front of me) that the final pin assignment in the digital_pin_to_bit_mask_PGM array is wrong. It currently assigns pin 15 to PB0. Digital pin 9 has already been assigned to PB0, so I think the last entry in digital_pin_to_bit_mask_PGM should be _BV(7) as that is the remaining unused pin in the PORTB block.

**Comment by TCWORLD** [comment]
You are indeed correct. I have made the necessary correction.

Thanks.
