### ISSUE TITLE
It can not work on my ATtiny24a ssu

### ISSUE THREAD

**Issue by segatecm** [TCWORLD/ATTinyCore#26]
Hi,
I download your project and unzip in my arduino IDE(1.06)  hardware folder.
and i make a new boards.txt as it:
attiny24-8.name=ATtiny24 (internal 8 MHz clock)
attiny24-8.bootloader.low_fuses=0xe2
attiny24-8.bootloader.high_fuses=0xdf
attiny24-8.bootloader.extended_fuses=0xff
attiny24-8.upload.maximum_size=2048
attiny24-8.bootloader.path=empty
attiny24-8.bootloader.file=empty24at16.hex
attiny24-8.build.mcu=attiny24
attiny24-8.build.f_cpu=8000000L
attiny24-8.build.core=tiny
attiny24-8.build.variant=tinyX4

i burn the bootloader to tiny24 and write a sketch:
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(3, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(3, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);              // wait for a second
}

i burn it to tiny24 but nothing happend.

i had try the code at https://github.com/damellis/attiny/archive/master.zip
it can works but it can not compile the Serial lib.
please help!

**Comment by TCWORLD** [comment]
That sketch wouldn't do anything meaningful. It sets the output low once every second. If you are expecting it to blink, you would have to add something to make it high.

**Comment by segatecm** [comment]
thanks for reply.
i change the code like this
void setup() {
// initialize digital pin 13 as an output.
pinMode(3, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
digitalWrite(3, LOW); // turn the LED off by making the voltage LOW
delay(1000); // wait for a second
digitalWrite(3, HIGH); // turn the LED off by making the voltage HIGH
delay(1000); // wait for a second
}

it do not blink too. 
but it can work with this lib,https://github.com/damellis/attiny/archive/master.zip

**Comment by TCWORLD** [comment]
If you turn verbose output on for compilation, you will see at the end it tells you in one of the commands towards the end a file path to something ending in ".elf". Could you send me that file so I can see how it has compiled the code.

It sounds more like an issue with programming it than compiling it as I haven't had any issues with the x4 series - use them a lot. The other thing to check is what pin do you have the LED connected to? Have you checked the diagram in the pins_arduino.h file to make sure the you have the correct digital pin number that corresponds to the pin you have the LED connected to?

**Comment by segatecm** [comment]
Hi TCWORLD, This post is reported with my attiny24, but it canot work. the LED connection is right.
Because I had try another lib: https://github.com/damellis/attiny. that can work.

C:\Users\cm\AppData\Local\Temp\build1839323202011094616.tmp\blink.cpp.elf C:\Users\cm\AppData\Local\Temp\build1839323202011094616.tmp\blink.cpp.hex 
Binary sketch size: 826 bytes (of a 2,048 byte maximum)

**Comment by TCWORLD** [comment]
Hi,
It's not that output that interests me. I truncated what you posted, you notice there is a file name ending with '.elf' there? That is the file that I need to see.
Looking at the output you posted, I haven't actually tested the core on Arduino 1.0.6.

**Comment by segatecm** [comment]
hi TCWORLD, i put the elf file on my web file driver:
http://pan.baidu.com/s/1o6Flo06
you can download it by click button "下载18kB" on the top right of the page.
Thanks for your help!

**Comment by TCWORLD** [comment]
(EDIT: Never mind, misread that.)

What you compiled seems to be ok, which suggests there is either a problem with the chip or it is not getting programmed properly.

**Comment by TCWORLD** [comment]
Actually, on closer inspection, I think you must have either an older version of the core or a different one as the pin mappings PROGMEM arrays in your .elf are incomplete.

Could you download the attiny core again, make sure to delete the copy you have, and then try compiling again.
If that doesn't work, could you try using an older version of the IDE (e.g. 1.0.5) and see if it works with that.

**Comment by segatecm** [comment]
HI TCWORLD,
I download your the new code on github, and using older IDE version 1.0.5,but it can not work either.
i upload elf at this link http://pan.baidu.com/s/1ntqQPw1
Maybe you can check it, thank for help!

**Comment by TCWORLD** [comment]
Ok, that .elf had the correct pin mappings.

Just for the sake of argument, try this sketch:

```
void setup() {
  pinMode(3,OUTPUT);
  digitalWrite(3,HIGH);
}
void loop() {}
```

Does digital pin 3 (Pin 6 of the chip) go high?
There seems nothing wrong with the way the code has compiled, which means it is more likely an issue with your hardware.

**Comment by segatecm** [comment]
hi TCWORLD, it work now.
but so weird the pin number is wrong.
my sketch like this:
int pin = 7;
// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(pin, OUTPUT);
  digitalWrite(pin, HIGH);
}

but the pin10 (PA3 (ADC3/T0/PCINT3)) on at24 is HIGH.

**Comment by TCWORLD** [comment]
Which is correct. If you look at the pins_arduino.h file in the variants/tinyX4/ folder it gives a diagram of how Arduino pin numbers map to physical pin numbers.

**Comment by segatecm** [comment]
I had seem another pin define at https://github.com/damellis/attiny/archive/master.zip
Which define is not as same as yours:

// ATMEL ATTINY84 / ARDUINO
//
//                                          +-\/-+
//                                 VCC  1|    |14  GND
//                      (D 10)  PB0  2|    |13  AREF (D  0)
//                       (D  9)  PB1  3|    |12  PA1  (D  1) 
//                                 PB3  4|    |11  PA2  (D  2) 
//  PWM  INT0  (D  8)  PB2  5|    |10  PA3  (D  3) 
//  PWM            (D  7)  PA7  6|    |9   PA4  (D  4) 
//  PWM            (D  6)  PA6  7|    |8   PA5  (D  5)        PWM
//                                           +----+

I dont know which is correct. but it look like as same as a hardware define.
I am a newbie to avr program, so thanks for your kindly help.

**Comment by TCWORLD** [comment]
The one defined in this core is correct for this core. The one defined for that core is correct for that core. I based my pin mappings on the original attiny core.

**Comment by segatecm** [comment]
ok,Thanks for your help!
I can use tiny24 now!
