### ISSUE TITLE
integrate attiny261 ?

### ISSUE THREAD

**Issue by wareck** [TCWORLD/ATTinyCore#7]
Can you explain me how to integrate attiny261 ? (I think is the same ac

**Comment by dewy721** [comment]
Actually, I just aggregated the cores made by others into a board.txt file
with submenus.

I don't know how to derive the fuse settings from scratch.

**Comment by TCWORLD** [comment]
The fuse settings will be the same for all of the AttinyX61 boards. The only difference between them in the boards.txt file is the size of the flash and the name of the part.

If you open the boards.txt file, there are entries for attiny861. Copy and paste one of those, change the name to attiny261 and change the maximum flash size to 2048.

**Comment by dewy721** [comment]
sweet! Thanks

**Comment by wareck** [comment]
Bonjour Duane Bishop,
Thanks a lot for your answer and integrate attiny261 !

FERNANDEZ Olivier, wareck@gmail.com

sweet! Thanks
